checkerboard:
  tile:
    size: 100
    lightColor: FFD2A6
    darkColor: A85D5D
  num:
    rows: 8
    cols: 8
  piece:
    fill:
      color:
        one: ED5564
        two: 434A54
    stroke:
      color:
        one: 762A32
        two: 0D0E10

    radius: 37.5